version: '3.5'

services:
  publisher:
    build: ./publisher
    restart: always
    #command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    depends_on:
      - mysql
      - redis
    #command: ["./wait-for-it.sh", "mysql:3308", "--", "python", "app.py"]
    volumes:
      - ./publisher:/app
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD: 'password'
    # links:
    #   - mysql
    ports:
      - 8000:8000
      - 3308
    expose:
     - 8000
    networks:
      - app-network
  subscriber:
    build: ./subscriber
    volumes:
      - ./subscriber:/app
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - app-network
  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - "./.mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'pwd'
      MYSQL_DATABASE: 'subscription'
      MYSQL_PASSWORD: 'pwd'
      MYSQL_USER: admin
    ports:
      - 3308:3306
    networks:
      - app-network
    expose:
      - 3306
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    expose:
      - 6379
    networks:
      - app-network
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - ./redis:/data
networks:
  app-network:
    driver: bridge